const ADD_CUSTOMER = 'ADD_CUSTOMER';
const GET_CUSTOMER = 'GET_CUSTOMER';
const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
const GET_ADDRESS = 'GET_ADDRESS';

export {ADD_CUSTOMER, GET_CUSTOMER, DELETE_CUSTOMER, GET_ADDRESS};
